### ISSUE TITLE
NOTIFY opcode has changed in Net::DNS 0.69

### ISSUE THREAD

**Issue by Krymson** [bradpeczka/tinydns-notify#1]
The opcode used for notify has changed for Net::DNS 0.69 to 0.71 with no backward compatibility.

I have a patch for this if you can give me push access to push a branch up.

**Comment by bradpeczka** [comment]
Sure thing, the invite will be with you shortly.

**Comment by bradpeczka** [comment]
Issue resolved in PR #2 which has been merged - many thanks!
